plugins {
    id 'com.android.application'
}

android {
    namespace 'com.austinslair.minecraftlce'
    compileSdk 35

    defaultConfig {
        applicationId 'com.austinslair.minecraftlce'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17'
            }
        }
    }

    sourceSets {
        main {
            assets {
                srcDirs = [
                    'src/main/assets',
                    '../../Minecraft.Client/Common/res',
                    '../../Minecraft.Client/Common/Media'
                ]
            }
        }
    }

    aaptOptions {
        noCompress 'png', 'ttf', 'swf', 'arc', 'pck', 'loc'
    }

    externalNativeBuild {
        cmake {
            path 'src/main/cpp/CMakeLists.txt'
            version '3.22.1'
        }
    }
}
